package builder

var tmpl = `// Code generated by github.com/gobuffalo/packr. DO NOT EDIT.

package {{.Name}}

import "github.com/pydio/packr"

// You can use the "packr clean" command to clean up this,
// and any other packr generated files.
func init() {
	{{- range $box := .Boxes }}
	packr.PackBoxLoader("{{$box.Name}}", func(){
	{{- range .Files }}
		_ = packr.PackJSONBytes("{{$box.Name}}", "{{.Name}}", "{{.Contents}}")
	{{- end }}
	})

	{{- end }}
}
`
